export const SPECIALTIES: Record<string, string[]> = {
  'maquillage-beaute': [
    'Maquillage mariée',
    'Maquillage soirée',
    'Maquillage naturel',
    'Maquillage oriental',
    'Maquillage permanent',
    'Rehaussement de cils',
    'Browlift / Sourcils',
    'Relooking',
  ],
  'coiffure-onglerie': [
    'Coiffure à domicile',
    'Coiffure mariée',
    'Tresses & nattes',
    'Lissage / Kératine',
    'Coloration',
    'Pose d\'ongles gel',
    'Nail art',
    'Faux ongles',
  ],
  'esthetique-bien-etre': [
    'Soins du visage',
    'Massage relaxant',
    'Épilation',
    'Soins du corps',
    'Gommage',
    'Pose de cils',
    'Microblading',
    'Hammam à domicile',
  ],
  'gateaux-sucreries': [
    'Layer cake',
    'Wedding cake',
    'Gâteau personnalisé',
    'Candy bar',
    'Macarons',
    'Cupcakes',
    'Cake design',
    'Gâteau halal',
  ],
  'photographie': [
    'Photo mariage',
    'Portrait',
    'Photo famille',
    'Photo événement',
    'Packshot produit',
    'Photo nouveau-né',
    'Grossesse',
    'Photo corporate',
  ],
  'videaste': [
    'Film de mariage',
    'Aftermovie',
    'Clip musical',
    'Vidéo événement',
    'Drone',
    'Publicité / Réels',
    'Vidéo corporate',
    'Teaser',
  ],
  'decoration-events': [
    'Décoration mariage',
    'Décoration anniversaire',
    'Babyshower',
    'Thème oriental',
    'Arche florale',
    'Table de fête',
    'Ballons & déco',
    'Location matériel',
  ],
  'dj-animation': [
    'DJ mariage',
    'DJ soirée',
    'DJ anniversaire',
    'Animateur',
    'Karaoké',
    'Sono & lumières',
    'Photobooth',
    'Spectacle',
  ],
  'bijoux-accessoires': [
    'Bijoux artisanaux',
    'Bijoux sur-mesure',
    'Parures mariée',
    'Accessoires mode',
    'Plaqué or',
    'Argent 925',
    'Piercing',
    'Sacs & maroquinerie',
  ],
  'mode-couture': [
    'Robe sur-mesure',
    'Retouches',
    'Abaya / Djellaba',
    'Costume homme',
    'Tenue de mariée',
    'Stylisme',
    'Broderie',
    'Vêtements enfants',
  ],
  'automobile': [
    'Lavage auto',
    'Climatisation',
    'Carrosserie',
    'Vitres teintées',
    'Covering',
    'Polissage',
    'Location de voiture',
    'Débosselage',
  ],
  'mariage': [
    'Wedding planner',
    'Coordination jour J',
    'Recherche de prestataires',
    'Mariage oriental',
    'Mariage civil',
    'Mariage religieux',
    'Voyage de noces',
    'Faire-parts',
  ],
  'artisans-fait-main': [
    'Broderie',
    'Tricot & crochet',
    'Poterie',
    'Macramé',
    'Tufting',
    'Couture créative',
    'Bijoux faits main',
    'Déco maison',
  ],
  'traiteur-cuisine': [
    'Traiteur oriental',
    'Traiteur africain',
    'Chef à domicile',
    'Buffet mariage',
    'Repas livré',
    'Cuisine halal',
    'Pâtisserie orientale',
    'Barbecue / Méchoui',
  ],
  'services-islam': [
    'Hijama',
    'Cours d\'arabe',
    'Cours de Coran',
    'Abayas & vêtements',
    'Traiteur halal',
    'Soins entre femmes',
    'Ruqya',
    'Livres islamiques',
  ],
  'cadeaux-personnalises': [
    'Box cadeaux',
    'Gravure',
    'Coffrets sur-mesure',
    'Cadeaux naissance',
    'Cadeaux mariage',
    'Photo sur objet',
    'Texte personnalisé',
    'Cadeaux entreprise',
  ],
  'bougies-parfums': [
    'Bougies artisanales',
    'Bougies parfumées',
    'Parfums naturels',
    'Diffuseurs',
    'Savons naturels',
    'Cosmétiques maison',
    'Huiles essentielles',
    'Coffrets bien-être',
  ],
  'personnalisation-textile': [
    'Flocage',
    'Impression DTF',
    'Broderie',
    'Tee-shirts personnalisés',
    'Sweats & hoodies',
    'Tenues d\'équipe',
    'Casquettes',
    'Sacs personnalisés',
  ],
  'voyages-aventures': [
    'Voyages groupés',
    'Randonnées',
    'Week-ends organisés',
    'Retraites bien-être',
    'Séjours halal',
    'Voyages entre femmes',
    'Road trips',
    'Circuits culturels',
  ],
  'autres': [],
}

export function getSpecialties(categorySlug: string): string[] {
  return SPECIALTIES[categorySlug] ?? []
}
